#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'
require 'yaml'

# Chronological list of source editions. Each revision category on the
# upstream wiki contains only the concepts changed that year (deltas). To
# produce a "wholly consistent" target edition (full state at that point
# in time), we walk sources in chronological order and let later sources
# override earlier ones for shared termids.
SOURCE_EDITIONS = %w[
  iala-1970-89
  iala-2009
  iala-2012
  iala-2015
  iala-2016
  iala-2017
  iala-2018
  iala-2022
  iala-2023
].freeze

# Each target edition's cumulative set includes itself and every prior source.
CUMULATIVE = {
  'iala-1970-89' => %w[iala-1970-89],
  'iala-2009'    => %w[iala-1970-89 iala-2009],
  'iala-2012'    => %w[iala-1970-89 iala-2009 iala-2012],
  'iala-2015'    => %w[iala-1970-89 iala-2009 iala-2012 iala-2015],
  'iala-2016'    => %w[iala-1970-89 iala-2009 iala-2012 iala-2015 iala-2016],
  'iala-2017'    => %w[iala-1970-89 iala-2009 iala-2012 iala-2015 iala-2016 iala-2017],
  'iala-2018'    => %w[iala-1970-89 iala-2009 iala-2012 iala-2015 iala-2016 iala-2017 iala-2018],
  'iala-2022'    => %w[iala-1970-89 iala-2009 iala-2012 iala-2015 iala-2016 iala-2017 iala-2018 iala-2022],
  'iala-2023'    => SOURCE_EDITIONS,
}.freeze

RAW = 'datasets_raw'
OUT = 'datasets'

# Preserve about-eng.md files that live alongside concepts/ (they are
# hand-written, not regenerated by the cumulative builder).
about_pages = {}
if File.directory?(OUT)
  Dir.glob("#{OUT}/*/about-*.md").each do |path|
    about_pages[path] = File.read(path)
  end
end

FileUtils.rm_rf(OUT)
FileUtils.mkdir_p(OUT)

about_pages.each do |path, content|
  FileUtils.mkdir_p(File.dirname(path))
  File.write(path, content)
end

CUMULATIVE.each do |target, sources|
  out_dir = File.join(OUT, target, 'concepts')
  FileUtils.mkdir_p(out_dir)
  merged_bib = {}
  concept_count = 0

  sources.each do |src|
    raw_concepts = File.join(RAW, src, 'concepts')
    next unless File.directory?(raw_concepts)

    # Later sources override earlier ones for shared termids. cp -f overwrites.
    Dir.glob("#{raw_concepts}/*.yaml").each do |yaml_file|
      FileUtils.cp(yaml_file, out_dir)
      concept_count += 1
    end

    bib_file = File.join(RAW, src, 'bibliography.yaml')
    next unless File.exist?(bib_file)
    docs = YAML.load_stream(File.read(bib_file))
    docs.each do |doc|
      next unless doc.is_a?(Hash)
      doc.each do |key, entry|
        merged_bib[key] = entry if entry.is_a?(Hash)
      end
    end
  end

  File.write(File.join(OUT, target, 'bibliography.yaml'), merged_bib.to_yaml)

  puts "#{target}: #{concept_count} concept files copied (cumulative sources: #{sources.size})"
end
